// Generated by https://quicktype.io

export interface CurrencyResponse {
  monto:                number;
  montoConTipoDeCambio: string;
  monedaOrigen:         string;
  monedaDestino:        string;
  tipoDeCambio:         number;
}


export interface UserCurrecy {
  user: CurrencyResponse;
}
